-- AlterTable
ALTER TABLE "Reservation" ALTER COLUMN "reservedMonth" DROP DEFAULT,
ALTER COLUMN "reservedMonth" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "reservedDay" DROP DEFAULT,
ALTER COLUMN "reservedDay" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "reservedHour" SET DEFAULT '01',
ALTER COLUMN "reservedHour" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "reservedMinutes" SET DEFAULT '00',
ALTER COLUMN "reservedMinutes" SET DATA TYPE VARCHAR(255);
