# Nombre de la aplicación
name = "court-reservation" 

# Versión de Node.js
[env]
NODE_VERSION = "18"
PORT = 8080

# Comandos de build
[build]
  - command = "npm install --shamefully-hoist"
  - command = "npm run build"
  - command = "npm lock -y"
  - command = "npm install -g @nestjs/cli"

# Comando de inicio  
[start] 
  command = "npx nest start"